### ISSUE TITLE
Change visibility of ChannelMonitor's cfg and servicename to protected

### ISSUE THREAD

**Issue by chhil** [jpos/jPOS-EE#249]
https://github.com/jpos/jPOS-EE/blob/master/modules/status/src/main/java/org/jpos/ee/status/ChannelMonitor.java#L31-L32

Please, can we change these 2 to protected?
I extend the channel monitor (different package name) and need access to the variables to allow additional commands like signon/signoff/key exchange etc, and I don't have my package structure like the ChannelMonitor's.

**Comment by ar** [comment]
I don't think you need to change the visibility of that variable. You can:

```
@Override
public void setConfiguration (Configuration cfg) {
    super.setConfiguration(cfg);  // this is important, of course.
    
    // here you can get ahold of whatever config you need.
}
```

Would that solve your requirement?

**Comment by chhil** [comment]
Silly me. Thats works for me.
