### ISSUE TITLE
Change DTD used from the SourceForge one to the hibernate one

### ISSUE THREAD

**Issue by chhil** [jpos/jPOS-EE#251]
**Change**
https://github.com/jpos/jPOS-EE/blob/1f857edcd47f1330daf14c4efb9e530ddf7bfcda/modules/status/src/main/resources/org/jpos/ee/status/Status.hbm.xml#L21

and 
https://github.com/jpos/jPOS-EE/blob/1f857edcd47f1330daf14c4efb9e530ddf7bfcda/modules/status/src/main/resources/org/jpos/ee/status/StatusTag.hbm.xml#L21

**from** 
```
<!DOCTYPE hibernate-mapping
  SYSTEM "http://hibernate.sourceforge.net/hibernate-mapping-3.0.dtd">
```

**to**

```
<!DOCTYPE hibernate-mapping 
  SYSTEM "http://www.hibernate.org/dtd/hibernate-mapping-3.0.dtd">
```

**Comment by ar** [comment]
Not that easy - see https://github.com/jpos/jPOS-EE/runs/7183459332?check_suite_focus=true#step:7:3843

```
[org.xml.sax.SAXParseException; cvc-complex-type.3.2.2: Attribute 'generated' is not allowed to appear in element 'property'.]
            at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:396)
            at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:377)
            at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:350)
            at org.hibernate.boot.cfgxml.internal.JaxbCfgProcessor.unmarshal(JaxbCfgProcessor.java:127)
```

**Comment by barspi** [comment]
Only `Status.hbm.xml` and `StatusTag.hbm.xml` are using the sourceforge DTD
All other entities in all other jPOS-EE modules are using  http://www.hibernate.org/dtd/hibernate-mapping-3.0.dtd and it seems to work, or at least they don't give that error.

**Comment by ar** [comment]
Can you send a PR @barspi ?

**Comment by barspi** [comment]
Sent #273
