### ISSUE TITLE
Make the Debug participant extend the doPrepare(...) method to get profile dump the debug participant's timing info

### ISSUE THREAD

**Issue by chhil** [jpos/jPOS-EE#256]
https://github.com/jpos/jPOS-EE/blob/6fbb795831fd9324811843ff3796e4783694717b/modules/txn/src/main/java/org/jpos/transaction/Debug.java#L26-L29

Since Debug.java extends the TxnSupport's prepare(...) method instead of doPrepare(...) the profiler does not create the checkpoint and no timing info is available for the debug participant.

Similarly abort can be changed to doPrepareForAbort(...)

**Comment by ar** [comment]
The Debug participant functionality have been incorporated into the TransactionManager itself. The main reason for doing that was to emit in the same LogEvent profiling information. We don't have Debug and Trace events separated anymore, they get automatically emitted by the TM at the end of every transaction (provided the debug is on, which is usually the case).

Regarding the commit ID, it's right there: `banknet-txnmgr-9:idle:1` - the 1 there is the commit ID.

**Comment by chhil** [comment]
Maybe we can document the following.

If you use the debug flag don't use the debug participant, otherwise you end up with 2 context log entries in the log.

**Comment by ar** [comment]
Done in jPOS-EE (https://github.com/jpos/jPOS-EE/commit/bc9ceff7cbc0f23c9e75c222e83dd88d9c66f5bf).

jPOS-EE.pdf has been updated, the new notice looks like this:

![Screen Shot 2022-07-21 at 16 06 35 ](https://user-images.githubusercontent.com/100354/180296135-680d8817-350c-492b-8ca4-3e979c8c3609.png)
