### ISSUE TITLE
A lot of check methods are not going through the entire list of params for validation

### ISSUE THREAD

**Issue by chhil** [jpos/jPOS-EE#266]
https://github.com/jpos/jPOS-EE/blob/a4684899b49fad4312ec1d9e37a255fc3aeaa4f9/modules/qrest/src/main/java/org/jpos/qrest/ValidateParams.java#L178-L190

return validParam(ctx, entry, value); 

should be changed to the following to return false only if the method returns false, else continue in the for loop 
```
if (!validParam(ctx, entry, value);)
  return false;
```

This was reported  (https://github.com/jpos/jPOS-EE/discussions/265)

**Comment by ar** [comment]
Good point @chhil - actually, `getResult()` can collect multiple errors at once, so we may want to go over ALL the parameters at once, and return `true` at the end only if all parameters are valid.

**Comment by ar** [comment]
Fixed by PR #267 - thank you @jrfinc 

Can you double-check @chhil this fixes the issue?

**Comment by ar** [comment]
Fixed in #267 - feel free to reopen if you see any issues.
