### ISSUE TITLE
Building Project

### ISSUE THREAD

**Issue by tafadzwagwena** [jpos/jPOS-EE#79]
running gradlew build, hangs on the following.
<=======------> 58% EXECUTING [6m 18s]
> :modules:qi-core:vaadinCompile

environment windows 7

**Comment by ar** [comment]
Probably a local issue, lack of memory? Try `--info` and `--stacktrace` to get some visibility.

Please note this works on the Travis builds https://travis-ci.org/jpos/jPOS-EE

**Comment by tafadzwagwena** [comment]
I have enabled  --info and  I get the following output  on the logfile below (gradlew --info InstallApp)
  logfile
Logging to file  jPOS-EE-master\modules\qi-core\build\logs\widgetset-compile.log

---------------Start of File-----------------------------------------------------------------------
INFO] Compiling module org.jpos.AppWidgetset
[ERROR] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
[ERROR] at java.util.Arrays.copyOf(Arrays.java:3332)
[ERROR] at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
[ERROR] at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:566)
[ERROR] at java.lang.StringBuilder.append(StringBuilder.java:181)
[ERROR] at com.google.gwt.dev.javac.JdtUtil.signature(JdtUtil.java:345)
[ERROR] at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:82)
[ERROR] at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:832)
[ERROR] at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.traverse(FieldDeclaration.java:343)
[ERROR] at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1353)
[ERROR] at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3933)
[ERROR] at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3971)
[ERROR] at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
[ERROR] at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:336)
[ERROR] at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:546)
[ERROR] at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:458)
[ERROR] at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1040)
[ERROR] at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
[ERROR] at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
[ERROR] at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
[ERROR] at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
[ERROR] at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
[ERROR] at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
[ERROR] at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[ERROR] at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[ERROR] at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[ERROR] at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[ERROR] at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[ERROR] at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[ERROR] at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[ERROR] at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[ERROR] at com.google.gwt.dev.Compiler.main(Compiler.java:125)
